---
title: 'Document'
output: html_document
---

## document
13110_50.docx

## Vegetation.Type
Forest and Woodland

## Map.Zones
50

## Geographic.Range
This system spans from the eastern edge of the Great Plains, south to the Ozarks and eastward to western Ohio and Kentucky. The northern boundary of this vegetation occurs in LANDFIRE map zone (MZ)50.

## Biophysical.Site.Description
This system occurs most commonly on interlobates where outwash, ice-contact and end moraine landforms are situated between former glacial lobes. Other landforms suitable for development of the dry oak forest are sandy lake plain and dunes. Common to all these landforms is somewhat excessively drained, acidic soil characterized by sand and loamy sand. Dry landscape settings, such as on western and southern aspects and upper slopes and ridge tops are conducive to the development of this system.

## Vegetation.Description
Oaks dominated the presettlement vegetation, especially white oak (Quercus alba), black oak (Quercus velutina), and bur oak (Quercus macrocarpa) (Bolliger et al. 2004). This system is distinguished from North-Central Interior Dry-Mesic Oak Forest and Woodland (1310) by stronger dominance of black oak and northern pin oak, and a general lack of red oak except in later seral stages. In Wisconsin, associates include black cherry (Prunus serotina), shagbark hickory (Carya ovata), and black walnut (Juglans nigra). Small trees associates include hop-hornbeam (Ostrya virginiana) and boxelder (Acer negundo). Common low woody shrubs include hazelnut (Corylus americana), brambles (Rubus spp.), black currant (Ribes cynosbati), and native roses (Rosa spp.). Graminoid species such as Carex pensylvanica, Danthonia spicata, and Andropogon gerardii are also common. In the most acidic lake plain physiographic systems, ericaceous shrubs such as wintergreen (Gualtheria procumbens), lowbush blueberry (Vaccinium angustifolium), huckleberry (Gaylussacia baccata) become common. Bracken fern (Pteridium aquilinum) can be dominant in the most nutrient poor outwash and lake plain landscapes.

## Disturbance.Description
The North-Central Interior Dry Oak Forest and Woodland is predominantly Fire Regime I, characterized by low-to-moderate severity surface fires. In Wisconsin, oak woodlands and forest occurred in a mosaic of small patches within a landscape dominated by oak savanna (Bolliger et al. 2004). Across the landscape, vegetation types varied based on fire frequency and severity. Grassland prairies burned frequently (annually or biennially) and were strongly associated with flat-to-slightly rolling terrain that effectively carried fire (Anderson 1999). Oak grubs (tree-sprout and shrub thickets) occurred where frequent prairie fires killed the tops of young trees that continue to sprout from deeply established root systems (Curtis 1959, Anderson and Bowles 1999). Savannas and woodlands developed within a moderate burning regime, with fire return times suggested to be between 5-15yrs. Closed-canopy oak forests would develop where fire return intervals stretched beyond 20-40yrs (Crow, 1988). If fire is excluded for several decades, more shade-tolerant and fire-sensitive species would gradually replace overstory oaks and oak regeneration is limited (Nowacki and Abrams 2008). Successional forest changes take more time in dry oak forests when site conditions are more xeric (Johnson et al. 2009). 

Historically, grazing would have similarly maintained open conditions in savannas and was probably an important contributing factor maintaining oak-dominated open lands (savannas and woodlands) in presettlement times (Anderson 2006). High deer populations can also limit oak regeneration (Rooney and Waller 2003). Ice-damage, periodic insect defoliation and the passenger pigeon (now extinct) may have likely contributed to increased oak canopy openings that facilitated light penetration to the forest floor, and, ultimately, greater possibility of germination and recruitment of oaks (McEwan et al. 2011). 

Archeological and ecological evidence suggests that Native Americans played a critical role in the development and maintenance of oak-hickory landscapes through fire ignition (Abrams and Nowacki 2008). However, the spatial extent of indigenous fire impact is unknown (Munoz et al. 2014). Lightning strikes would have provided an additional source of ignition. Regardless of the source, fire was historically an important control on ecological systems in this region, including dry oak forest and woodland.

## Scale.Description
In Wisconsin, pre-European American settlement oak woodlands and forests occurred infrequently in small patches, within a larger matrix of oak savanna (Bolliger et al. 2004). Fire, the dominant disturbance, occurred frequently across large-scale landscapes.

## Adjacency.or.Identification.Concerns
This type intergrades and can be easily confused with North-Central Interior Dry-Mesic Oak Forest and Woodland (1310). Fire suppression within the last century has allowed this system to be converted to that system on the loamier soils within the historic range of this type. This type can be distinguished from the Dry-Mesic Oak Forest and Woodland by somewhat sandier soils or more exposed topographic settings with higher incoming solar radiation (south- and west-facing slopes).
 
This type can intergrade with North-Central Oak Barrens (1395), especially in 222R and northwestern 222K, but can be distinguished by occupying sites that are less excessively drained and siltier than those of the barrens. Soils are generally more well-drained than for the Dry-Mesic Oak Forest and Woodland, but are not excessively sandy as for the Oak Barrens.

This type is also found on steep, dry south and west facing slopes and the tops of bluffs in Section 222L where it intergrades with Paleozoic Plateau Bluff and Talus (1517).

In Wisconsin, especially near the Tension Zone or on bluffs in the Driftless Area, this cover type can also include some components of pine (especially white pine).

Oak forest patches are virtually always integrated in the larger landscape scale with mesic maple-dominated forests, dry-mesic oak-hickory forests, dry oak barrens, and oak savanna. Mesic maple forests were relegated to those areas where fire was restricted through facilitation by an edaphic factor such as heavy-textured soil or high water table or by natural fire breaks such as bodies of water and slightly protected depressions. Prolonged intervals (100-150yrs) were needed for maples to manifest their dominance. Dry-mesic oak-hickory forests often occurred adjacent to dry oak forests, defined by a topographic position that had more amenable well-drained soil, lower solar radiation, better moisture conditions, and more protection from drying winds and recurring fires. Lower slopes on north and east aspects were typical of oak-hickory forests whereas ridge tops and upper slopes on south and west aspects favored dry oak forests. Oak forests also graded into savannas and barrens (i.e., oak openings) when fire intervals shortened to the point where woody regeneration of overstory tree species was limited. Exposed areas where wind could carry flames at great distances tend to exhibit more savanna vegetation structure than a closed oak forest. In areas where flat outwash extended beyond ice-contact terrain or end moraine, savannas would typically occur in the former abutting a closed forest on the latter landforms. Fires often burned from a west to east direction and stopped on the western edge of rivers (Gleason, 1913), leaving eastern edges forested. NOTE: red maple problem is more prevalent in eastern United States, especially not on dry oak forests in Wisconsin.

## Issues.or.Problems
Due to the absence of fire, dry oak forests in Wisconsin are succeeding to brush and eastern red cedar on dry sites and to boxelder, elms, black cherry, and red maple on more mesic sites (Epstein et al. 2002).

Native grazing, due to higher deer densities than historically (at least in Wisconsin) further suppress recruitment of oaks and exacerbates the trend toward closed-canopy mesophytic species. Invasive species, including garlic mustard (Alliaria petiolata), buckthorn (Rhamnus cathartica), and honeysuckle (Lonicera spp.) are becoming increasingly prevalent in the understories of some stands (Schulte et al. 2011).

Today, with fragmentation, development, and mesophytic species invasion, few original dry oak forest remain. However, succession of previous oak barrens to closed oak forests can add to the total area of current dry oak forests.

## Native.Uncharacteristic.Conditions
Red maple may or may not be a problem in southern Wisconsin oak forests, particularly not dry oak forests. See the silviculture handbook: http://dnr.wi.gov/topic/ForestManagement/documents/24315/51.pdf

